CREATE DATABASE ShoppingMarket DEFAULT CHARACTER SET 'utf8'
  DEFAULT COLLATE 'utf8_unicode_ci';

USE ShoppingMarket;

CREATE TABLE UserPrincipal (
  UserId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(30) NOT NULL,
  HashedPassword BINARY(60) NOT NULL,
  NickName VARCHAR(255) NULL,
  TelPhone VARCHAR(30) NOT NULL,
  PostCode VARCHAR(30) NULL,
  Address VARCHAR(255) NULL,
  Email VARCHAR(255) NOT NULL,
  IsNonExpired VARCHAR(10),
  IsAccountEnabled VARCHAR(10),
  UNIQUE KEY UserPrincipal_Username (Username)
) ENGINE = InnoDB;

CREATE TABLE Orders(
  OrderId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Price INTEGER UNSIGNED NOT NULL,
  UserId BIGINT UNSIGNED NOT NULL,
  Status TEXT,
  DateCreated TIMESTAMP(6) NULL,
  CONSTRAINT Order_UserId FOREIGN KEY (UserId)
    REFERENCES UserPrincipal (UserId) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE ShoppingItem (
  ShoppingItemId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Category VARCHAR(255) NOT NULL,
  Description TEXT,
  Price DOUBLE UNSIGNED NOT NULL,
  Image BLOB NULL
) ENGINE = InnoDB;

CREATE TABLE Orders_CartItemForOrder(
  SortKey SMALLINT NOT NULL ,
  OrderId BIGINT UNSIGNED NOT NULL,
  CartItemForOrderId BIGINT UNSIGNED NOT NULL,
  CONSTRAINT Orders_CartItemForOrder_Order FOREIGN KEY (OrderId)
    REFERENCES Orders(OrderId) ON DELETE CASCADE,
  CONSTRAINT Orders_CartItemForOrder_CartItemForOrder FOREIGN KEY (CartItemForOrderId)
    REFERENCES CartItemForOrder(CartItemForOrderId) ON DELETE CASCADE,
  INDEX Orders_OrderedCartItems (OrderId, SortKey, CartItemForOrderId)
) ENGINE = InnoDB;

CREATE TABLE Cart(
  CartId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  UserId BIGINT UNSIGNED NOT NULL,
  CONSTRAINT Cart_UserId FOREIGN KEY (UserId)
    REFERENCES UserPrincipal (UserId)
) ENGINE  = InnoDB;

CREATE TABLE CartItem(
  CartItemId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ShoppingItemId BIGINT UNSIGNED NOT NULL,
  Amount BIGINT UNSIGNED NOT NULL,
  CONSTRAINT CartItem_ShoppingItemId FOREIGN KEY (ShoppingItemId)
    REFERENCES ShoppingItem(ShoppingItemId)
) ENGINE = InnoDB;

CREATE TABLE CartItemForOrder(
  CartItemForOrderId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ShoppingItemId BIGINT UNSIGNED NOT NULL,
  Amount BIGINT UNSIGNED NOT NULL,
  CONSTRAINT CartItemForOrder_ShoppingItemId FOREIGN KEY (ShoppingItemId)
  REFERENCES ShoppingItem(ShoppingItemId)
) ENGINE = InnoDB;

CREATE TABLE Cart_CartItem(
  SortKey SMALLINT NOT NULL,
  CartId BIGINT UNSIGNED NOT NULL,
  CartItemId BIGINT UNSIGNED NOT NULL,
  CONSTRAINT Cart_CartItem_Cart FOREIGN KEY (CartId)
    REFERENCES Cart(CartId) ON DELETE CASCADE
) ENGINE = InnoDB;

